### ISSUE TITLE
Seems like it is using the wrong decryption key

### ISSUE THREAD

**Issue by r-a-i** [tai/decrypt-xyz3w#4]
bash-3.2$ java DecryptXYZ3W DaVinci1ProFilamentHolder.3w foo.zip
Exception in thread "main" javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2260)
	at DecryptXYZ3W.main(DecryptXYZ3W.java:51)
bash-3.2$ ls -lh foo.zip 
-rw-r--r--  1 xxx  staff     0B Nov 16 00:59 foo.zip

**Comment by FattiMei** [comment]
I suggest you try this key"@xyzprinting.com@xyzprinting.com". I found this in the code of miniMover, a similar but more extended github project
